### ISSUE TITLE
cmake: gpssim segfault on posix sitl

### ISSUE THREAD

**Issue by jgoppert** [jgoppert/Firmware#21]
@mcharleb, have you seen this before, any ideas?

``` bash
jgoppert@gnubox:~/git/px4/cmake-Firmware$ gdb ./build_posix-sitl_simple/main 
...
WARN  1          starting task wkr_high (file /home/jgoppert/git/px4/cmake-Firmware/src/platforms/posix/px4_layer/px4_posix_tasks.cpp line 146)
[New Thread 0x7ffff67d5700 (LWP 31756)]
[New Thread 0x7ffff6fd6700 (LWP 31755)]
WARN  2442       starting task wkr_low (file /home/jgoppert/git/px4/cmake-Firmware/src/platforms/posix/px4_layer/px4_posix_tasks.cpp line 146)
[New Thread 0x7ffff57d3700 (LWP 31758)]
WARN  4187       starting task wkr_hrt (file /home/jgoppert/git/px4/cmake-Firmware/src/platforms/posix/px4_layer/px4_posix_tasks.cpp line 146)
[Thread 0x7ffff6fd6700 (LWP 31755) exited]
[New Thread 0x7fffeffff700 (LWP 31760)]
App name: mainapp
Enter a command and its args:
uorb start
----------------------------------
Running: uorb
Returning: uorb
Enter a command and its args:
gpssim start
----------------------------------
Running: gpssim
WARN  11356190   starting task gps (file /home/jgoppert/git/px4/cmake-Firmware/src/platforms/posix/px4_layer/px4_posix_tasks.cpp line 146)
[New Thread 0x7fffeeffd700 (LWP 31788)]
gps lock
gps unlock

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeeffd700 (LWP 31788)]
0x00000000004132f8 in Simulator::getGPSSample(unsigned char*, int) ()
(gdb) backtrace
#0  0x00000000004132f8 in Simulator::getGPSSample(unsigned char*, int) ()
#1  0x000000000040cf33 in GPSSIM::receive(int) ()
#2  0x000000000040d1d6 in GPSSIM::task_main() ()
#3  0x000000000040c080 in entry_adapter(void*) ()
#4  0x00007ffff7bc4182 in start_thread (arg=0x7fffeeffd700) at pthread_create.c:312
#5  0x00007ffff72e747d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) 
```

**Comment by mcharleb** [comment]
I have not seen this, but when we get back to that point I'll have a look.
